// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `Northwind`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=tron\sqlexpressonmbp;Initial Catalog=StackOverflow;Integrated Security=True`
//     Include Views:          `True`

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Massive.DAL.Models
{
    /// <summary>
    /// A class which represents the PostTypes table.
    /// </summary>
	[Table("PostTypes")]
	public partial class PostType
	{
		public virtual int Id { get; set; }
		public virtual string Type { get; set; }
	}

    /// <summary>
    /// A class which represents the PostsTags table.
    /// </summary>
	[Table("PostsTags")]
	public partial class PostsTag
	{
		public virtual int PostId { get; set; }
		public virtual string Tag { get; set; }
		public virtual string SiteId { get; set; }
	}

    /// <summary>
    /// A class which represents the Badges table.
    /// </summary>
	[Table("Badges")]
	public partial class Badge
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int? UserId { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? CreationDate { get; set; }
	}

    /// <summary>
    /// A class which represents the Comments table.
    /// </summary>
	[Table("Comments")]
	public partial class Comment
	{
		public virtual int Id { get; set; }
		public virtual int? PostId { get; set; }
		public virtual int? Score { get; set; }
		public virtual string Text { get; set; }
		public virtual DateTime? CreationDate { get; set; }
		public virtual int? UserId { get; set; }
	}

    /// <summary>
    /// A class which represents the Posts table.
    /// </summary>
	[Table("Posts")]
	public partial class Post
	{
		public virtual int Id { get; set; }
		public virtual int? PostTypeId { get; set; }
		public virtual int? AcceptedAnswerId { get; set; }
		public virtual DateTime? CreationDate { get; set; }
		public virtual int? Score { get; set; }
		public virtual int? ViewCount { get; set; }
		public virtual string Body { get; set; }
		public virtual int? OwnerUserId { get; set; }
		public virtual string OwnerDisplayName { get; set; }
		public virtual int? LastEditorUserId { get; set; }
		public virtual DateTime? LastEditDate { get; set; }
		public virtual DateTime? LastActivityDate { get; set; }
		public virtual string Title { get; set; }
		public virtual string Tags { get; set; }
		public virtual int? AnswerCount { get; set; }
		public virtual int? CommentCount { get; set; }
		public virtual int? FavoriteCount { get; set; }
		public virtual DateTime? ClosedDate { get; set; }
		public virtual int? ParentId { get; set; }
		public virtual DateTime? CommunityOwnedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the Users table.
    /// </summary>
	[Table("Users")]
	public partial class User
	{
		public virtual int Id { get; set; }
		public virtual int? Reputation { get; set; }
		public virtual DateTime? CreationDate { get; set; }
		public virtual string DisplayName { get; set; }
		public virtual DateTime? LastAccessDate { get; set; }
		public virtual string WebsiteUrl { get; set; }
		public virtual string Location { get; set; }
		public virtual int? Age { get; set; }
		public virtual string AboutMe { get; set; }
		public virtual int? Views { get; set; }
		public virtual int? UpVotes { get; set; }
		public virtual int? DownVotes { get; set; }
	}

    /// <summary>
    /// A class which represents the Votes table.
    /// </summary>
	[Table("Votes")]
	public partial class Vote
	{
		public virtual int Id { get; set; }
		public virtual int? PostId { get; set; }
		public virtual int? VoteTypeId { get; set; }
		public virtual DateTime? CreationDate { get; set; }
	}

    /// <summary>
    /// A class which represents the Tags table.
    /// </summary>
	[Table("Tags")]
	public partial class Tag
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string TagName { get; set; }
	}

    /// <summary>
    /// A class which represents the PostTags table.
    /// </summary>
	[Table("PostTags")]
	public partial class PostTag
	{
		public virtual int? PostId { get; set; }
		public virtual int? TagId { get; set; }
	}

    /// <summary>
    /// A class which represents the VoteTypes table.
    /// </summary>
	[Table("VoteTypes")]
	public partial class VoteType
	{
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
	}

}
